version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/output:/app/output
    environment:
      - WIKI_JS_URL=http://wikijs:3001
      - WIKI_JS_API_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGkiOjIsImdycCI6MSwiaWF0IjoxNzUxNDQwNjU2LCJleHAiOjE3ODI5OTgyNTYsImF1ZCI6InVybjp3aWtpLmpzIiwiaXNzIjoidXJuOndpa2kuanMifQ.WKurWweL1iFoCAgNm5QV7MSHntyBayJd0p2a_IoJ7xAe99O3J6Pz1n3QontW3d7jYa8nP91lTYbiu8-7iMM_p3fPyxboRAqI-b15yP_Tq3AgvyhneU7wGp7RhytjWub_xL1s5u9fwBrtzp-PlA05jaXxz7pfmD--ZfOxF7ne1dqHD36pAEutdK8-Rvd8BI7yClRxCREO5pBs4JJDYO_7L-C7s8GIYvulBYASwmelPppw35Ed3MV3XFIaCOMsV4B_hIL21AMffQoIhC7Bv2UWd_3Hrtdb90N0ZlwlxbKvlxrn7xL7kD6-v7NRyoAbeDulcMrqS2Qj80ed6dwaETJs1A
      - WIKI_JS_DEFAULT_PATH=/home
    depends_on:
      - wikijs

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  wikijs:
    image: requarks/wiki:2
    ports:
      - "3001:3000"  # Avoid conflict with frontend on port 3000
    environment:
      - DB_TYPE=sqlite
      - DB_FILEPATH=/wiki/data/wiki.db
    volumes:
      - ./wikijs-data:/wiki/data

# docker-compose up --build